# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
default: &default
  github_app_token: <%= ENV['GITHUB_APP_TOKEN'] %>

development:
  <<: *default
  github_app_token: 802ac2d61850630a8d178a6197817c926bfc8e96
  secret_key_base: fb2c4ca1bd71cea2078e20f46a904f8e0ec38f3eb2e0c06b5cc0eb36f6b118374f2e4961cba2bc56620c0bf9d3a6a9d65833faa1f22d6659d2e3ead821c03b58

test:
  <<: *default
  secret_key_base: 1e0762aa023c1797ddc74f8411c64aef76041cf8b9dfcfc225ec9b3ae9528de194031917cd4648b139f82b6eb560972b3abec43d6cce7b582d9f8cc0e6fbe49a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
